### PR TITLE
Added db support to stt

### PR DESCRIPTION
**Pull request by gksoriginals**
1. Added db support to stt
2. User from client can save save endpoint to save the session

### CODE REVIEW

**Comment by bsbarkur** [comment]
Add Redis installation also?

**Comment by bsbarkur** [comment]
Rest looks pretty good.

**Comment by gksoriginals** [comment]
@bsbarkur done

**Comment by bsbarkur** [comment]
There's conflicts still, instructor commit hasn't been updated ?

**Pull request merged**
